### ISSUE TITLE
[WIP] Firefox extension

### ISSUE THREAD

**Issue by ghost** [iHydra/flatdarkness#9]
Currently i am rewriting and removing useless code to support firefox without big changes.

Shit to do
- [x] Release test extension for beta testers [flat_darkness_hf_theme-1.0.0.zip](https://github.com/iHydra/flatdarkness/files/1250583/flat_darkness_hf_theme-1.0.0.zip) (don't expect a lot functions to work like settings)
- [ ] Fix not found bugs
- [ ] Add last needed keys to mainfest for publish
- [ ] Port rewrite for chrome source
- [ ] Start writing automatic tarvis build to support one source for all WebExtension browsers

Note: extension will support only firefox 57+, to get firefox 57 nightly build [click here](https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly)

Done stuff:
- Rewrite manifest, remove useless permissions, add firefox specific keys
- Test run for original code passed with bugs
- Rewrite worker fully support only firefox (change 1 variable and will support both (tarvis build))

**Comment by yfdyh000** [comment]
typo: 47+ to 57+

**Comment by iHydra** [comment]
Did not give you permission to work on this. I do not vouch, trust, nor support your work.
